name: Build package
on:
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.5f1-base-0
    steps: 
      - name: install git
        run: apt-get install software-properties-common && add-apt-repository ppa:git-core/ppa -y && apt-get update && apt-get install git -y
      - name: version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: master
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          format: "${major}.${minor}.${patch}"
          short_tags: true
          bump_each_commit: true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: write manifest
        run: mkdir Packages && mv manifest.dist.json Packages/manifest.json
      - name: write license file
        run: echo '${{ secrets.UNITY_LICENSE }}' | tr -d '\r' > /opt/Unity_v2020.x.ulf
        # assets need to be in an assets folder, unity will create a whole project around it
      - name: activate license
        run: unity-editor -quit -batchmode -manualLicenseFile /opt/Unity_v2020.x.ulf -logfile - || true
        working-directory: Assets
      - name: pack package
        run: unity-editor -batchmode  -nographics -quit  -projectPath .. -exportPackage "Assets/AAAPE" "Assets/ScriptTemplates" "./AAAPE-DOTS.unitypackage"  -logfile -
        working-directory: Assets
      - name: release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./AAAPE-DOTS.unitypackage
          asset_name: AAAPE-DOTS.${{ steps.version.outputs.version }}.unitypackage
          asset_content_type: application/octet-stream